### ISSUE TITLE
Epic: Make mqtt-server container friendly

### ISSUE THREAD

**Issue by Lapiniot** [Lapiniot/Net.MQTT#2]
We need to make some project adjustments to make application containers friendly. This includes both app's code and build configuration enhancements.

- [x] https://github.com/Lapiniot/Net.MQTT/issues/3
- [x] https://github.com/Lapiniot/Net.MQTT/issues/4
- [x] https://github.com/Lapiniot/Net.MQTT/issues/5
- [x] https://github.com/Lapiniot/Net.MQTT/issues/6
- [x] https://github.com/Lapiniot/Net.MQTT/issues/8
- [x] https://github.com/Lapiniot/Net.MQTT/issues/9
- [x] https://github.com/Lapiniot/Net.MQTT/issues/11

**Comment by Lapiniot** [comment]
#3
